```{r loading libraries - EDA metadata, message=FALSE, eval=TRUE, include=TRUE}
#import::from(.from = SummarizedExperiment, colData, assay)
import::from(.from = DT, datatable)
import::from(.from = ggplot2, .all=TRUE)
import::from(.from = DataExplorer, plot_bar)
#import::from(.from = tableone, CreateTableOne)
import::from(.from = dplyr, group_by, count)

```

```{r EDA metadata - loading objects, message=FALSE, eval=TRUE, include=TRUE, cache=TRUE}
experiment_name="nk_tum_immunoedit_complete"
output_dir <- paste0(results_dir, "/",experiment_name,"/") # "/home/rstudio/workspace/results_dir/nk_tum_immunoedit_complete/" #  
# results_dir defined in the nk_immunoediting.Rmd file

eda_plots_dir <- paste0(output_dir, "eda_plots/")
dir.create(eda_plots_dir)

# raw and filtered dds
precomputed_objects_filename <- paste0(experiment_name, "_dds_objects.RData") #"nk_tum_immunoedit_complete_dds_objects.RData" #
precomputed_objects_file <- file.path(output_dir, precomputed_objects_filename)

# log2 and vsd transformed
precomputed_transf_objects_filename <- "nk_tum_immunoedit_complete_log2_vsd_filt_objects.RData"
precomputed_transf_objects_file <- file.path(output_dir, precomputed_transf_objects_filename)

# check if object loaded if not load
if(!exists(precomputed_objects_file)){
  load(precomputed_objects_file)
  load(precomputed_transf_objects_file)
} 

metadata <- tibble::as_tibble(SummarizedExperiment::colData(dds_filt))

key_metadata <- metadata %>%
  dplyr::select(experiment, condition_tp,condition, timepoint_cell_harvesting, day_cell_harvesting, cell_line_label, technical_replicate) 

# saving metadata
openxlsx::write.xlsx(metadata, file = file.path(output_dir, paste0(experiment_name, "_metadata.xlsx")))

```

Metadata overview:

```{r EDA metadata - overview, eval=TRUE, message=FALSE, cache=TRUE, include=TRUE}
# 'KeyTable', ,'FixedHeader', 'Responsive', 'Scroller', 'ColReorder'
# to add show entries - https://stackoverflow.com/questions/64976684/how-to-have-buttons-and-a-show-entries-using-datatables-dt-in-rmarkdown

DT::datatable(data = metadata,
              caption = 'Metadata overview',
              filter = 'top',
              class = 'hover',
    extensions = c('Buttons'), options = list(
      pageLength = 5,
      #autoWidth = TRUE
      #fixedHeader = TRUE, 
      scrollX = TRUE,
      #scrollY = TRUE,
      #scrollY = 200,
      #deferRender = TRUE,
      #scroller = TRUE,
      #colReorder = TRUE,
      #keys = TRUE,
      searchHighlight = TRUE,
      dom = 'Blfrtip',
      buttons = list('copy', 'colvis', list(
        extend = 'collection',
        buttons = c('csv', 'excel', 'pdf'),
        text = 'Download'
      ))
  )
)
```

```{r EDA metadata - key variables, message=FALSE, eval=TRUE, include=TRUE, cache=TRUE, fig.show='hide'}
# 1. metadata overview
# 2. composition per experiment
# 3. relationship (table(x, y)) - to see how many variables we have in each category; data imbalance!?

# frequency of key variables ----
# fig.show='hide' - to supress plotting here
key_variables_freq <- DataExplorer::plot_bar(key_metadata, order_bar=TRUE, ggtheme = theme_bw(), title = "Frequency of key variables")

# table of variable frequency per experiment ----
key_variables_tableOne <- tableone::CreateTableOne(vars = colnames(dplyr::select(key_metadata, -experiment)), 
                           strata = c("experiment"), 
                           data = key_metadata)

# relate variables ----
# cat_cat_plot <- ggplot(data = key_metadata, color=cell_line_label) +
#   geom_count(mapping = aes(x = experiment, y = condition_tp)) #+   facet_wrap(~cell_line_label)

cat_cat_counts <- key_metadata %>% 
  dplyr::group_by(cell_line_label) %>%
  dplyr::count(experiment, condition_tp)

cat_cat_plot <- ggplot(data = cat_cat_counts, mapping = aes(x = experiment, y = condition_tp, group=cell_line_label)) +
  #     geom_tile(mapping = aes(fill = n))
  geom_point(mapping=aes(size=n, color=cell_line_label), position = position_dodge(width=0.5)) +
  scale_size(breaks = c(0,1,2,3,4,5,6)) +
  # ggrepel::geom_label_repel(aes(label = n),
  #                           box.padding   = 0.35, 
  #                           point.padding = 0.5,
  #                           segment.color = 'grey50') +
  ggtitle("Number of samples pre condition/experiment.") +
  theme_bw()
```

Frequency of key variable:

```{r EDA metadata - key variables freq, message=FALSE, eval=TRUE, include=TRUE, fig.dim = c(10, 10)}
print(key_variables_freq$page_1)

ggsave(filename = paste0(eda_plots_dir, "key_variables_freq_plot.png"), 
       plot=key_variables_freq$page_1,
       width = 20, height = 20, units = "cm")
```

Overview of number of samples in different categories (experiment, condition,...).:

```{r EDA metadata - key variables table, message=FALSE, eval=TRUE, include=TRUE}
#print(key_variables_tableOne$CatTable)
tableone::kableone(key_variables_tableOne$CatTable,
                   caption = "Overview of number of samples in different categories (experiment, condition,...).") %>%
  kableExtra::kable_material(c("striped", "hover"))
```

Plot of number of samples in each condition across different experiments:

```{r EDA metadata - key variables relate, message=FALSE, eval=TRUE, include=TRUE, fig.dim = c(12, 10)}
print(cat_cat_plot)

ggsave(filename = paste0(eda_plots_dir, "key_variables_relate_plot.png"), 
       plot=cat_cat_plot,
       width = 20, height = 20, units = "cm")
```


